-- Esquema de la base del juego.
-- Ejecutar en Supabase -> SQL Editor. Se puede correr mas de una vez sin romper nada.
-- Replica las tablas que creaba Django (backend/scores/migrations/0001_initial.py).

create table if not exists public.scores_player (
  id          bigint generated by default as identity primary key,
  email       varchar(254) not null unique,
  total_coins integer not null default 0 check (total_coins >= 0),
  best_score  integer not null default 0 check (best_score >= 0),
  created_at  timestamptz not null default now()
);

create table if not exists public.scores_gamesession (
  id               bigint generated by default as identity primary key,
  player_id        bigint not null references public.scores_player (id) on delete cascade,
  started_at       timestamptz not null default now(),
  ended_at         timestamptz,
  coins_reported   integer not null default 0 check (coins_reported >= 0),
  score_reported   integer not null default 0 check (score_reported >= 0),
  is_valid         boolean not null default true,
  rejection_reason varchar(255) not null default ''
);

create index if not exists scores_gamesession_player_id_idx
  on public.scores_gamesession (player_id);

-- RLS activado y sin politicas: con la clave publica nadie lee ni escribe filas.
alter table public.scores_player enable row level security;
alter table public.scores_gamesession enable row level security;

-- Solo el Worker (clave secreta = rol service_role) usa estas tablas.
-- Desde mayo de 2026 Supabase no concede estos permisos automaticamente en proyectos nuevos.
revoke all on public.scores_player, public.scores_gamesession from anon, authenticated;
grant select, insert, update on public.scores_player, public.scores_gamesession to service_role;
grant usage, select on all sequences in schema public to service_role;
